hooks/useToggle.tsx
- 관련 이슈: useToggle 훅 제작
- 어디서든 사용 가능한 useToggle 기능 제작
=> useToggle 훅 제작

components/gnb/Hammenu/index.tsx, components/gnb/index.tsx, pages/_app.tsx
- 관련 이슈: Gnb ui 수정
- 가로 스크롤 생기는 버그 수정
- 글자색 빠진부분 수정
https://github.com/GilDongMu/gildongmu/assets/148840514/e0d02769-263c-4363-84f2-bcef46aadfe1
=> Gnb ui 수정

components/form/input/DatePickerInput.tsx, components/form/input/IntroTextarea.tsx, components/form/input/TagInput.tsx, components/form/signupForm/index.tsx
- 관련 이슈: 회원가입 페이지 input border 디자인 수정, 가입하기 버튼 hover 추가
- 회원가입 페이지 input border 피그마 디자인에 맞춰 다시 수정했습니다.
- 가입하기 버튼 hover 색 추가했습니다.
https://github.com/GilDongMu/gildongmu/assets/137983583/c91b0cae-7288-4389-a1db-8aa9884c7b31
=> 회원가입 input border 수정, 가입하기 버튼 hover

components/gnb/Dropdown/index.tsx, components/gnb/Hammenu/index.tsx, components/gnb/index.tsx
- 관련 이슈: gnb hover 수정
- hover시 색상이 잘못되어있던 것을 수정
=> gnb hover 수정

components/ui/button.tsx, styles/globals.css, tailwind.config.ts
- 관련 이슈: 여러 곳에서 공통적으로 사용되게끔 shadcn/ui 버튼 컴포넌트 수정
- shadcn/ui 버튼을 import 했을 때 variant를 정하고 일부 클래스만 추가하면 되도록 variant 수정
=>  버튼 공용 컴포넌트 구현

.prettierrc, components/modal/alert/button.tsx, components/ui/button.tsx, pages/index.tsx
- 관련 이슈: 모달 버튼 ui 수정
- 모달 버튼을 shadcn/ui 버튼으로 수정
=> 모달 버튼 ui 수정

components/main/contents/travel.tsx
- 관련 이슈: 메인페이지 여행글 카드 영역 디자인 수정
- 메인페이지 여행글 카드 영역 디자인 수정했습니다.
=> 메인페이지 여행글 카드 영역 디자인 수정

components/ui/button.tsx, pages/index.tsx
- 관련 이슈: 모달 버튼 ui hover 디자인 추가 및 수정
- 모달 버튼 ui hover 디자인 추가 및 수정
=> 모달 버튼 ui hover 디자인 추가 및 수정

lib/api/axios.js, tsconfig.json
- 관련 이슈: axios 기본 세팅
- axios 기본 세팅을 했습니다
=> axios 기본 세팅

components/card/index.tsx, components/gnb/index.tsx, components/travel/contents/cardGrid.tsx, components/travel/contents/filter.tsx, components/travel/contents/filterBtn.tsx, components/travel/contents/paging.tsx, package-lock.json, package.json, pages/travel/index.tsx, tailwind.config.ts
- 관련 이슈: 전체글 페이지 제작
- 테블릿, 모바일 디자인이 나옴으로 맞춰서 변경
- 반응형에 맞춰서 카드도 조금 수정
https://github.com/GilDongMu/gildongmu/assets/148840514/9ae16334-cd7c-444a-802e-0efc22dd7a7d
=> 전체글 페이지 제작

components/card/index.tsx
- 관련 이슈: 카드 임시 데이터 넣어두기
- api 명세서 확인 후 해당 데이터 mock으로 만들어 사용
=> 카드 임시 데이터 넣어두기

components/card/index.tsx
- 관련 이슈: 카드 스타일 빠진거 수정
- 스타일이 하나 빠져 수정
=> 카드 스타일 빠진거 수정

components/gnb/Hammenu/index.tsx, components/gnb/index.tsx, pages/_app.tsx
- 관련 이슈: gnb색상 변경 수정
- gnb 색상 상세글에서도 바뀌도록 수정
=> gnb색상 변경 수정

components/form/input/DatePickerInput.tsx, components/form/input/ImageUploadInput.tsx, components/form/input/RadioInput.tsx, components/form/input/RangeDatePickerInput.tsx, components/form/input/TagInput.tsx, components/form/signupForm/index.tsx
- 관련 이슈: 회원가입 api 연동
- any 타입 수정
- 비밀번호 눈 모양 수정
- 회원가입 api 연동 / 중복 이메일 검사 api 연동
=> 회원가입 api 연동

components/form/signupForm/index.tsx
- 관련이슈 : 회원가입 성공 시 로그인 페이지 이동
- 회원가입에 성공하면 로그인 페이지로 이동합니다.
=> 회원가입 성공 시 로그인 페이지 이동

pages/login/index.tsx
- 관련 이슈: 로그인 페이지 오류 사항 업데이트
- router.push로 변경
- fetch -> axios
- Alert 모달 수정
- input이 하나라도 비어있으면 로그인 버튼 disabled
=> 로그인 페이지 오류 수정

components/detail/article/contents/destination/descriptionImages/index.tsx, components/detail/article/contents/destination/index.tsx, components/detail/article/contents/index.tsx, components/detail/article/contents/recruitment/index.tsx, components/detail/article/index.tsx, components/detail/article/title/index.tsx, lib/api/detail/index.ts, lib/api/detail/type.ts, pages/travel/[Id]/detail/index.tsx
- 상세페이지 데이터 넣기
- 상세페이지 api route 수정
- 상세페이지 데이터 추가(타이틀부분 찜하기 기능, 댓글관련 데이터 제외)
=> 상세페이지/eonpain/146

components/detail/article/contents/comments/register/commentOfcomment/index.tsx, components/detail/article/contents/destination/descriptionImages/index.tsx
- 상세페이지 이미지 클래스 속성 수정, 불필요한 드롭다운 삭제
- 상세페이지 이미지 클래스 속성 수정, 불필요한 드롭다운 삭제
=> 상세페이지 이미지 클래스 속성 수정, 불필요한 드롭다운 삭제

components/card/index.tsx, components/community/commulist/index.tsx, components/community/header/index.tsx, components/header/index.tsx, components/mainCard/index.tsx, components/travel/contents/filter.tsx, components/travel/contents/filterBtn.tsx, hooks/isMobile.ts, pages/travel/index.tsx, styles/globals.css
- 전체글 / 소통공간 / gnb 디자인 지적당한 부분 수정
- 지적해주신 부분 디자인 수정
=>  전체글 / 소통공간 / gnb 디자인 지적당한 부분 수정

components/community/commuchat/index.tsx, components/community/commulist/index.tsx, components/dropdown/index.tsx, components/gnb/index.tsx, hooks/useCookie.tsx, lib/api/chat/index.ts, package-lock.json, package.json, pages/community/[id]/index.tsx, pages/login/index.tsx
- 소통공간 데이터 연결 준비
- 소통공간 데이터 연결 준비
- socket.io import 해서 준비
- 빌드할 때 에러나던거 수정
=> 소통공간 데이터 연결 준비

components/detail/article/contents/comments/index.tsx, components/detail/article/contents/comments/my/commentOfcomment/index.tsx, components/detail/article/contents/comments/my/index.tsx, components/detail/article/contents/comments/my/secret/commentOfcomment/index.tsx, components/detail/article/contents/comments/my/secret/index.tsx, components/detail/article/contents/destination/descriptionImages/index.tsx, components/detail/article/contents/destination/index.tsx, components/detail/article/contents/recruitment/index.tsx, components/detail/article/contents/sort/index.tsx, components/detail/article/index.tsx, components/detail/header/index.tsx
- 상세페이지 디자인 수정 필요
- 상세페이지 필터클릭 시 이동하는 부분의 스타일, 위치 수정
- 상세페이지 여행지 이미지 테두리 추가
- 모든 댓글 밑의 구분선 실선으로 통일
- 상세페이지 헤더부분 디자인 수정
- 상세페이지 드롭다운 부분 반응형 디자인 추가
- 상세페이지에서 스크롤 시 필터배경색이 변하게 하는 트리거 부분 위치를 수정
=> 상세페이지 디자인 수정

components/form/socialSignupForm/index.tsx, pages/login/index.tsx, pages/oauth2/login/index.tsx, pages/oauth2/signup/index.tsx
- 로그인 페이지 디자인 수정
- 로그인 에러 모달 수정
- 버튼 반응형
- 회원가입 버튼 색깔 수정
- 위아래 패딩 맞추기
- "존재하지 않는 이메일입니다."라는 모달 나오게 하기
=> 로그인 페이지 디자인 수정 & 로그인 에러 모달 수정

components/detail/article/title/index.tsx, components/modal/button.tsx, components/modal/index.tsx, pages/_app.tsx
- 엑세스 토큰 없을 시 로그인 필요 모달 뜨는 기능
- 엑세스 토큰 없을 시 로그인 필요 모달이 뜹니다.
=> 로그인 필요 모달 ui 구현 및 기능 구현

components/detail/article/title/index.tsx, pages/travel/[Id]/detail/index.tsx
- 상세페이지 찜하기 / 찜 취소 기능 필요
- 상세페이지 찜하기 / 찜 취소 기능 구현
=> 상세페이지 찜하기 /찜 취소 기능 구현

components/form/socialSignupForm/index.tsx, pages/login/index.tsx, pages/oauth2/login/index.tsx, pages/oauth2/signup/index.tsx
- 로그인 페이지 디자인 & 기능 수정
- 메인 이미지 삽입
- 로그인 시 에러 수정
- 버튼 디자인 수정
=> 로그인 페이지 디자인 & 기능 수정

components/detail/article/title/index.tsx, components/form/editForm/index.tsx, components/form/input/ContentInput.tsx, components/form/input/CounterInput.tsx, components/form/input/DatePickerInput.tsx, components/form/input/IntroTextarea.tsx, components/form/input/MultipleImageUploadInput.tsx, components/form/input/RadioInput.tsx, components/form/input/RangeDatePickerInput.tsx, components/form/input/TagInput.tsx, components/form/mypageForm/index.tsx, components/form/signupForm/index.tsx, components/form/writeForm/index.tsx, pages/404.tsx, pages/community/[id]/index.tsx, pages/login/index.tsx, pages/mypage/index.tsx, pages/signup/index.tsx, pages/travel/[Id]/detail/edit/index.tsx, pages/write/index.tsx
- 로그인 페이지 디자인 수정
- 피그마와 맞지 않은 디자인 수정
=> 로그인 페이지 디자인 수정 및 디자인 1차 검수

components/detail/article/title/index.tsx, components/detail/header/index.tsx, lib/api/bookmarks/index.ts, lib/api/detail/index.ts, lib/api/detail/type.ts
- 상세페이지 신청하기 기능 필요
- 상세페이지 신청하기/취소하기 기능 구현(미완성)
- 상세페이지 찜하기 토글기능 구현
- 상세페이지 뒤로가기 버튼 기능 구현
=> 상세페이지 신청하기 기능

next.config.js, package.json, target.js
- 배포 cors 에러 수정
- 배포 cors 에러 수정
=> 배포 cors 에러 수정
